- name: Deploy microservice to EKS
  hosts: localhost
  tasks:
    - name: Set Kubernetes context
      command: aws eks update-kubeconfig --name guberapandian --region ap-southeast-1

    - name: Deploy Helm chart
      community.kubernetes.helm:
        name: "my-microservice"
        chart_ref: "./charts/my-microservice"
        release_namespace: "my-namespace"
        values:
          image:
            repository: "762233769537.dkr.ecr.ap-southeast-1.amazonaws.com/gubera-deployment"
            tag: "{{ lookup('env', 'BUILD_NUMBER') }}"
