---
- name: Deploy microservice to EKS
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set Kubernetes context
      command: kubectl config use-context your-kube-context
      register: kubectl_context

    - name: Check if Helm is installed
      command: helm version
      register: helm_installed
      failed_when: helm_installed.rc != 0

    - name: Deploy Helm chart
      command: /usr/local/bin/helm install my-release ./charts/my-microservice --namespace=my-namespace --values ./charts/my-microservice/values.yaml
      args:
        chdir: ./charts/my-microservice
      register: helm_deployment
      failed_when: helm_deployment.rc != 0

    - name: Output Helm deployment result
      debug:
        var: helm_deployment.stdout_lines

    - name: Verify deployment
      command: kubectl get pods --namespace=my-namespace
      register: kubectl_pods

    - name: Output list of pods
      debug:
        var: kubectl_pods.stdout_lines
